
---
title: "Evaluating a Search Engine"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r  echo=FALSE}
ui <- basicPage(
    textOutput('task'),
    textOutput('task_description'),
    textInput("txt", "Enter the answer below:"),
    #verbatimTextOutput("default"),
    verbatimTextOutput("placeholder", placeholder = TRUE),
    sliderInput("n", "Number of observations", 2, 1000, 500),
    plotOutput("plot")
    
    # imageOutput('count')
  )
server <- function(input, output) {
    
    # Anything that calls autoInvalidate will automatically invalidate
    # every 2 seconds.
    autoInvalidate <- reactiveTimer(2000) # 20 seconds 
    
    # observe({
    # 
    #   
    # })
    
    # Generate a new histogram each time the timer fires, but not when
    # input$n changes.
    output$plot <- renderPlot({
      autoInvalidate()
      hist(rnorm(isolate(input$n)))
    })
    output$task <-renderText({
      autoInvalidate()
      "TASK" 
      # tasks[i]
      # ':'
    })
    output$task_description <-renderText({
      autoInvalidate()
      "Description" 
      # tasks[i]
      # ':'
    })
    #output$default <- renderText({ input$txt })
    output$placeholder <- renderText({ 
      autoInvalidate()
      isolate(input$txt) })
    # output$count <- renderImage({
    #   autoInvalidate()
    #   countdown(minutes = 10, seconds = 0)
    # })
  }
  
  shinyApp(ui, server)

```



